### PR TITLE
!! Breaking changes !! Direct use of child items instead of dumb components as slides

### PR DESCRIPTION
**Pull request by Jonarod**
@bd-arc 
This is my suggestion to solve ticket #28 .

### CODE REVIEW

**Comment by Exilz** [comment]
Hi @Jonarod, thanks for the PR. I was actually thinking about making this change too. Most components work this way, so it should be easier to pick up this carousel for someone new.

However, we support a lot of props right now, have you tested thoroughly that everything still works ?
Your code looks fine to me anyway :)

**Comment by Jonarod** [comment]
Sorry, I did not tested all props at all, really I put the code as is. I
suggest your team run tests as I imagine you have more use cases than me.
Between, I do not understand all props expected behaviors...
However, I can assure you these props work perfectly for me (Android
environment):
                        firstItem
                        inactiveSlideScale
                        inactiveSlideOpacity
                        enableMomentum
                        swipeThreshold
                        sliderWidth
                        itemWidth
                        slideStyle
                        containerCustomStyle
                        contentContainerCustomStyle
                        showsHorizontalScrollIndicator
                        snapOnAndroid

On a side note, while updating, I was quite unsure about the
ShouldComponentUpdate() function, so make sure it fits what you expected.
And I do NOT need autoplay at all so I did not tested it.

Ping me if I can help :)

**Comment by bd-arc** [comment]
@Jonarod Thank you for the PR and the info! As @Exilz said, this looks good :) Nevertheless, we'll make sure to run a few tests before merging it.

**Comment by bd-arc** [comment]
@Jonarod We had to deal with an issue: children were being rendered before props had a chance to update, which was problematic when items' length was changing. We also cleaned up the file a bit and updated the example.

Thanks a lot for you work! The new version has been published to npm ;)

**Pull request merged**
