### PR TITLE
Animate opacity and scale continuously with scroll value

### PR DESCRIPTION
**Pull request by hammadj**
This will really improve the fluidity of swiping between slides when using the opacity and scale options.

Before:
carouselbefore

After:
carouselafter2

### CODE REVIEW

**Comment by bd-arc** [comment]
Hey @hammadj,

Thanks for the PR that honestly looks pretty awesome! I'm going to take a bit of time to review it properly and make sure that there is no side-effect, but I really like the idea ;-)

**Comment by bd-arc** [comment]
At first glance, I see at least two drawbacks:
- animations will no longer be powered by the native driver (I added a prop `useNativeOnScroll` to the carousel to enable native-powered scroll, but I don't think it will do much for slide's animation itself)
- user will no longer be able to use custom animation functions and options (for example, I always use the plugin with a custom spring animation).

Any idea about how to overcome this?

**Comment by hammadj** [comment]
@bd-arc 

- Animations will still be powered by the native driver. The animation is an interpolation of the scroll position, which uses native driver, so the animation will also be native.
- Since this animation goes with the scroll position, there isn't any "animation function" to begin with. Its not linear or spring or anything else, its just based on how the user scrolls it. When it comes to the animation of the "scrollToIndex", react-native doesn't allow customizing that already so we cant change that.

If we want to preserve backwards compatibility with existing behaviour, we can have an option to disable animating with the scroll value.

**Comment by bd-arc** [comment]
@hammadj Thanks for the precisions; they confirm my own conclusion. I'm going to add this feature anyway because the end result is clearly what is the best for the plugin.

Note that I had to update the code to account for side-effects and to optimize a thing or two, as you can see in [this commit](https://github.com/archriss/react-native-snap-carousel/commit/6bb15c81603b445c8c8d639b7831336fac578fb2). Unfortunately, it means that I can't merge your PR. This bothers me since you deserve to be seen as a contributor :-( But I'll make sure to mention you both in the releases notes and the changelog.

Thank you again for the great idea 👍

**Comment by bd-arc** [comment]
Hi @hammadj,

Just wanted to let you know that I've just published [version `3.2.0`](https://github.com/archriss/react-native-snap-carousel/releases/tag/v3.2.0) which, along with other updates, features your idea ;-)

**Comment by hammadj** [comment]
Awesome, thank you!

**Pull request closed without merging**
