### PR TITLE
Added prop `inactiveDotStyle` to Pagination component

### PR DESCRIPTION
**Pull request by naffiq**
This is related to issue #114

### CODE REVIEW

**Comment by bd-arc** [comment]
@naffiq I'm going to merge the huge `flatlist` branch first. Then, if your branch still has no conflicts with the base branch I'll merge it ;-)

**Comment by bd-arc** [comment]
@naffiq There is a small conflict because, in the `flatlist` branch, I made sure to keep backward compatibility with RN versions older than `0.44.x`.

Do you mind rebasing on `master` and using the same syntax as in [this commit](https://github.com/archriss/react-native-snap-carousel/commit/292a75f0f418ea179df14da4c7485a831cfece0a)?

**Comment by naffiq** [comment]
@bd-arc resolved this one, hope now it's ready 👍

**Comment by bd-arc** [comment]
@naffiq That's perfect, thank you very much :-)

I'm going to:
- add two props in order to animate color change
- add a prop to allow custom dots components

and then I will publish it all!

**Comment by naffiq** [comment]
@bd-arc Yay! Glad to help, think the issue can be closed now :)

**Pull request merged**
