### PR TITLE
Fix null-pointer-exception

### LINKED ISSUE #166: Hot reloading doesn't work
It crashes with the error `Cannot read property 'scrollToIndex' of null` and a warning of `Can only update a mounted or mounting component. This usually means you called setState, replaceState or forceUpdate on a unmounted component. This is a no-op. Please check the code for the Carousel component`

### PR DESCRIPTION
**Pull request by entropitor**
I think this should fix #166

### CODE REVIEW

**Comment by bd-arc** [comment]
Hi @entropitor,

Thanks for the PR! It turns out that I'm currently working on a few fixes and that I already came up with something along the lines of what you've done.

I'll let you know as soon as the fixes are published in order for you to try it out and let me know if the PR is still needed.

**Comment by jerolimov** [comment]
Hey, have a similar Exception in our app. See below. I think this would fix our problem (hard to reproduce), too.

```
null is not an object (evaluating 'this._listRef.scrollToOffset')

Stack:
- value@index.android.bundle:205:2194
- index.android.bundle:994:5820
- index.android.bundle:23:1366
- o@index.android.bundle:23:571
- callTimers@index.android.bundle:23:2778
- value@index.android.bundle:18:2975
- index.android.bundle:18:280
- value@index.android.bundle:18:2426
- callFunctionReturnFlushedQueue@index.android.bundle:18:252
```

**Comment by jerolimov** [comment]
Releasing this as 3.2.4 would be great. So that your bigger chances could be tested in a new minor version?? Thanks both for creating and improving this module 👍

**Comment by bd-arc** [comment]
@entropitor @jerolimov Hey guys!

The issue should be fixed in the "soon-to-be-merged" [`loop` branch](https://github.com/archriss/react-native-snap-carousel/tree/loop). Can you confirm? To try it:
```
"react-native-snap-carousel": "https://github.com/archriss/react-native-snap-carousel#18acafa"

**Pull request closed without merging**
