### PR TITLE
Update package.json deps for RN 0.47

### PR DESCRIPTION
**Pull request by giehlman**
See https://github.com/react-native-community/react-native-linear-gradient/commit/4799a1d001c4e8853d0e5fc80ec20ccb844dc008

### CODE REVIEW

**Comment by bd-arc** [comment]
Hi @giehlman,

Thanks for the PR, but there is no need for it since "^2.1.0" means that the latest "2.x" version [will automatically be retrieved](https://stackoverflow.com/a/22345808/8412141) when running `npm install` or `yarn` ;-)

**Comment by bd-arc** [comment]
Did you have an issue with version `2.2.0` of `react-native-linear-gradient` not being downloaded?

**Comment by giehlman** [comment]
Hi @bd-arc, mega sry, my bad!

Yes, I had the issue that it checked out version 2.1.0 in the examples dir. `./example/yarn.lock` tells me:

> react-native-linear-gradient@^2.1.0:
>   version "2.1.0"
>   resolved "https://registry.yarnpkg.com/react-native-linear-gradient/-/react-native-linear-gradient-2.1.0.tgz#2cbf4a061fef5c74d1256da425caf9fe893c94e2"
>   dependencies:
>     prop-types "^15.5.10"

which results in the issue fixed by https://github.com/react-native-community/react-native-linear-gradient/commit/4799a1d001c4e8853d0e5fc80ec20ccb844dc008.

Yarn version used is `0.27.5`, didn't check back with npm, but I assume the registry will be the same. I also looked into the registry (https://registry.yarnpkg.com/react-native-linear-gradient/) which provides the correct latest:

>  "dist-tags": {
>     "latest": "2.3.0"
>   }

Current workaround is either to apply the fix manually in the android sources or force the checkout of v2.2.0/latest.

Sorry that I couldn't help any further!

**Comment by bd-arc** [comment]
Absolutely no worries!

Thanks for the detailed description. To be honest, I regularly have issues with Yarn's cache and I end up deleting the `nodes_modules` and reinstalling all the dependencies on a regular basis.

Do you mind trying it and letting me know if version `2.3.0` is properly installed then?

**Comment by giehlman** [comment]
You are correct. I did a couple of checks and I can confirm that either you are lucky on the first try :) or you can get the latest version by doing a `yarn upgrade`.

Unfortunately, just deleting the `node_modules` did not work on my system unless I manually adjusted the package.json to at least `^2.2.0` and then ran a `yarn install` again. Maybe some interference with the package-lock or peers...

**Comment by bd-arc** [comment]
Well, that's a bummer.

Since I need to make a few adjustments to the example, I'll make sure to update the version in `package.json`. Thank you for bringing this to my attention :-)

**Pull request closed without merging**
