### PR TITLE
Loop Bug

### PR DESCRIPTION
**Pull request by suhanmoon**
Fixed a bug when moving left or right when setting loop={true}

### Platforms affected
all

### What does this PR do?
loop bug fix

### What testing has been done on this change?
Set to loop true.
Moving to the left immediately after loading, moving to the right, moving as animation.

### Tested features checklist

- [ ] Default setup ([example](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L46-L87))
- [ ] Carousels with and without momentum enabled ([prop `enableMomentum`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] Vertical carousels ([prop `vertical`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] Slide alignment ([prop `activeSlideAlignment`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#style-and-animation))
- [ ] Autoplay ([prop `autoplay`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#autoplay))
- [x] Loop mode ([prop `loop`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#loop))
- [ ] `ScrollView`/`FlatList` carousels ([prop `useScrollView`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] [Callback methods](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#callbacks)
- [ ] [`ParallaxImage` component](https://github.com/archriss/react-native-snap-carousel#parallaximage-component)
- [ ] [`Pagination` component](https://github.com/archriss/react-native-snap-carousel#pagination-component)
- [ ] [Layouts and custom interpolations](https://github.com/archriss/react-native-snap-carousel#layouts-and-custom-interpolations)

### CODE REVIEW

**Comment by bd-arc** [comment]
Hi @suhanmoon,

Thanks for the PR!

To be honest, I do see how this fix is supposed to help with the loop issue. Could you please elaborate on that a little further?

**Comment by suhanmoon** [comment]
This Full width, 3 items set.

1. Left-to-Right Swipe
2. Move to the back (Animated) after swiping.

**Comment by oliverdolgener** [comment]
I can confirm this fixes the issue that causes a scroll animation to be played when `loop` is enabled and the user swipes to the right immediately after the component has been mounted.

**Comment by zabojad** [comment]
@bd-arc I also confirm it fixes the issue we have in loop mode with the animation being played after reaching a cloned item.

**Comment by zabojad** [comment]
In my opinion, we should even have this on line 274:
```js
this._snapToItem(nextFirstItem, false, false, false, false);
```
No need to trigger the callbacks again...

**Comment by bd-arc** [comment]
Available in version `3.8.0`.

**Comment by Saad9624** [comment]
comment out this line under Crousel.js
return this._carouselRef && this._carouselRef.getNode && this._carouselRef.getNode();

Thanks me later!

**Pull request merged**
