### PR TITLE
fix carousel loop flickering when combined with pagination component

### PR DESCRIPTION
**Pull request by muhamad-rizki**
### Platforms affected
android

### What does this PR do?
changed active dot index to internal component state, i have updated the example usage, but maybe you need to update the doc of pagination, im sorry i cant do that, i have limited English words.
issue related #232, #303, #304 

### What testing has been done on this change?
testing on real device, RN 0.55.4, JS Dev Mode On/Off

### Tested features checklist

- [x] Default setup ([example](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L46-L87))
- [ ] Carousels with and without momentum enabled ([prop `enableMomentum`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] Vertical carousels ([prop `vertical`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] Slide alignment ([prop `activeSlideAlignment`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#style-and-animation))
- [ ] Autoplay ([prop `autoplay`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#autoplay))
- [x] Loop mode ([prop `loop`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#loop))
- [ ] `ScrollView`/`FlatList` carousels ([prop `useScrollView`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [x] [Callback methods](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#callbacks)
- [ ] [`ParallaxImage` component](https://github.com/archriss/react-native-snap-carousel#parallaximage-component)
- [x] [`Pagination` component](https://github.com/archriss/react-native-snap-carousel#pagination-component)
- [ ] [Layouts and custom interpolations](https://github.com/archriss/react-native-snap-carousel#layouts-and-custom-interpolations)

### IMPRTANT NOTE
its still flickering if called on onSnapToItem, to fix it, I disabled fireCallback then I used lodash to find index of item and call setActiveDotIndex from onSnapToItem function

### CODE REVIEW

**Comment by bd-arc** [comment]
Hey @muhamad-rizki,

Thanks for the PR! I'm not sure that this is the best solution, but it's a step in the right direction. I'll see if I can think of something based on your solution and I'll make sure to keep you posted ;-)

**Comment by Xerus2000** [comment]
Can you please merge this? The flickering is super annoying, and this seems like a good and simple fix.

**Comment by saifahn** [comment]
@bd-arc, has any progress been made on a solution to this? We are having the same problem too.

**Comment by bd-arc** [comment]
@Xerus2000 @saifahn Have you had a chance to try the PR yet?

If it solves the issue and doesn't introduce any side effect, I'll be willing to merge it.

**Comment by Natkarock** [comment]
> @Xerus2000 @saifahn Have you had a chance to try the PR yet?
> 
> If it solves the issue and doesn't introduce any side effect, I'll be willing to merge it.

this PR not solved flickering problem in my case

**Comment by premhowli** [comment]
still seeing this issue. anybody got it solved?

**Comment by abdultocarcility** [comment]
I got resolved by adding SafeAreaView with my component

Platform->iOS

**Comment by swiftserieschannel** [comment]
muhamad-rizki its working fine now thank you so much for the solution.

**Comment by mohitkmr170** [comment]
Flickering on Android still not resolved, please update with a working solution for the same.

**Comment by pedrohcdo** [comment]
I solved this with:

 <Carousel 
        data={your_data}
        loop={true}
        loopClonesPerSide={your_data.length}/>

**Comment by akhila-antony** [comment]
This can be fixed by referring https://github.com/archriss/react-native-snap-carousel/issues/189#issuecomment-603014215. It works for me.

**Comment by bhavna-18** [comment]
Doesn't fixed for me.

**Comment by Balasnest** [comment]
> still seeing this issue. anybody got it solved?

still facing same. Any workaround for this?

**Comment by viratkohli3797** [comment]
Is there anyone who got the flickering issue for android? 

PS: works fine in IOS.

**Comment by toanpv-2417** [comment]
i do with https://github.com/meliorence/react-native-snap-carousel/issues/189#issuecomment-603014215
it work well , anyone can try !

**Pull request closed without merging**
