### PR TITLE
Fix RTL issues

### PR DESCRIPTION
**Pull request by ShaMan123**
### Platforms affected
Android

### What does this PR do?
Try to fix RTL issues

### What testing has been done on this change?
`DEV` mode only (yes I know that it's against the guideline)

### Tested features checklist

- [x] Default setup ([example](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L46-L87))
- [x] Carousels with and without momentum enabled ([prop `enableMomentum`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [x] **FAILED** Vertical carousels ([prop `vertical`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior)) - **doesn't work in current version either**
- [x] Slide alignment ([prop `activeSlideAlignment`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#style-and-animation))
- [x] Autoplay ([prop `autoplay`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#autoplay))
- [x] **WORKS ONLY WITH AUTOPLAY** Loop mode ([prop `loop`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#loop))
- [x] `ScrollView`/`FlatList` carousels ([prop `useScrollView`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [x] [Callback methods](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#callbacks)
- [x] [`ParallaxImage` component](https://github.com/archriss/react-native-snap-carousel#parallaximage-component)
- [x] [`Pagination` component](https://github.com/archriss/react-native-snap-carousel#pagination-component)
- [x] **NEEDS WORK & TESTING** [Layouts and custom interpolations](https://github.com/archriss/react-native-snap-carousel#layouts-and-custom-interpolations)

This is a fantastic project!

### CODE REVIEW

**Comment by bd-arc** [comment]
Hey @ShaMan123,

Thanks a lot for taking a stab at fixing the RTL behavior! I know how complicated this is, so I appreciate your help.

Two thoughts at this point:
- There is a lot of dead code in your PR — console logs, commented code (lines 1116-1148). Can you get rid of it?
- Is there a reason why you've updated the code in `Pagination` doc?

**Comment by ShaMan123** [comment]
I Will address dead code.
I updated the doc because after setting up `Pagination` as described the scroll behavior flickered at the first/second slide change due to `setState`

**Comment by ShaMan123** [comment]
@bd-arc cleaned the code.
Notice that as part of this PR I've commented the `inverted` prop because it didsn't behave properly.
See [line 1231](https://github.com/ShaMan123/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L1231)

**Comment by ShaMan123** [comment]
check out the getters `realIndex` & `currentIndex` => I don't know what's the difference between them. 
I've changed `realIndex` so it returns the index used by the developer (not the internal index used by the class). e.g. if the class is `rtl` then `internalIndex = 0` needs to be refactored before sent to the developer: `currentIndex` should equal `length - 1`. Same notion when using `loop` prop.
This is extremely important! I think `currentIndex` should be changed like wise but before changing wanted to better understand their purpose.

**Pull request closed without merging**
