### PR TITLE
Expose onScroll prop

### PR DESCRIPTION
**Pull request by radko93**
Allow the user to use `onScroll` prop from `ScrollView`.

### CODE REVIEW

**Comment by bd-arc** [comment]
Hey @radko93,
Could you describe a typical use case for which you would need such a prop?

**Comment by radko93** [comment]
We use it to animate the change of the content that depends on a Carousel page/position.
E.g. we have a carousel of book covers and we change the description below the carousel before we even snap to a certain element.

**Comment by bd-arc** [comment]
@radko93 Ok, I see. In order to keep file formatting consistent, could you add a semi-colon at the end of the line? I will then merge your PR and publish a new release.

**Comment by radko93** [comment]
I updated the PR.

**Comment by bd-arc** [comment]
@radko93 Published version `2.1.3` of the plugin includes your PR ;-)

**Comment by bd-arc** [comment]
@radko93 I don't know if you've had a chance to test you PR, but unfortunately this doesn't work. This is because `onScroll` is overridden by plugin's implementation.

That's why I've just published version 2.1.4 that adds prop `onScrollViewScroll` which should suits your needs.

**Comment by radko93** [comment]
We were using it from my fork so it should work. We pass it from plugins implementation method, not from ScrollView directly https://github.com/archriss/react-native-snap-carousel/pull/69/commits/2d23311d81176c089d89471a76516291ba370687#diff-168726dbe96b3ce427e7fedce31bb0bcR282.

**Comment by bd-arc** [comment]
@radko93 I see what you mean but this wasn't working, neither for us nor for other users. To be honest, I'm not sure why this wouldn't work; it might be related to some changes introduced with React 16.

`onScrollViewScroll` will do the trick though.

**Comment by bd-arc** [comment]
@radko93 Since I was unsatisfied with the fact that your solution didn't seem to work although it should have, I tried again today.

Well, now it seems to work as expected. I don't know if it has to do with recent React and/or React Native changes... ¯\\_(ツ)_/¯

Anyway, I'll expose `onScroll` again and deprecate `onScrollViewScroll`.

**Comment by radko93** [comment]
Yeah, this was strange. Thanks for replying.

**Pull request merged**
