### PR TITLE
[4.0.0-beta.x] Get correct carousel ref for RN 0.62.x

### PR DESCRIPTION
**Pull request by r0b0t3d**
### Platforms affected
Android & iOS

### What does this PR do?
There is api change since RN 0.62.x, so calling `getNode` is no longer necessary. This PR just make sure get the correct ref for both 0.62.x and below.

### What testing has been done on this change?
- Carousel works well and no error with `snapToItem` call (Tested on RN 0.62.2 and 0.61.5 by @alessandro-bottamedi)

### Tested features checklist

- [ ] Default setup ([example](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L46-L87))
- [ ] Carousels with and without momentum enabled ([prop `enableMomentum`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] Vertical carousels ([prop `vertical`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] Slide alignment ([prop `activeSlideAlignment`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#style-and-animation))
- [ ] Autoplay ([prop `autoplay`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#autoplay))
- [ ] Loop mode ([prop `loop`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#loop))
- [x] `ScrollView`/`FlatList` carousels ([prop `useScrollView`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] [Callback methods](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#callbacks)
- [ ] [`ParallaxImage` component](https://github.com/archriss/react-native-snap-carousel#parallaximage-component)
- [ ] [`Pagination` component](https://github.com/archriss/react-native-snap-carousel#pagination-component)
- [ ] [Layouts and custom interpolations](https://github.com/archriss/react-native-snap-carousel#layouts-and-custom-interpolations)

### CODE REVIEW

**Comment by r0b0t3d** [comment]
@bd-arc I used same code base that branch from master to create PR. it got conflict with `example/yarn.lock` that you removed

**Comment by r0b0t3d** [comment]
I was wrong, conflict in Camera.js. Just resolved conflict

**Comment by bd-arc** [comment]
Sorry @r0b0t3d but this adds unneeded commits.

Think you can start from `v4.0.0-beta.x` and just create one commit with your update?

**Comment by r0b0t3d** [comment]
@bd-arc created #702

**Pull request closed without merging**
