### PR TITLE
fix(Carousel): fix a workaround for zindex in flatlist making carouse…

### PR DESCRIPTION
**Pull request by CarbonC**
…l crash on android

### Tested features checklist

- [ ] Default setup ([example](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L46-L87))
- [ ] Carousels with and without momentum enabled ([prop `enableMomentum`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] Vertical carousels ([prop `vertical`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] Slide alignment ([prop `activeSlideAlignment`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#style-and-animation))
- [ ] Autoplay ([prop `autoplay`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#autoplay))
- [ ] Loop mode ([prop `loop`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#loop))
- [ ] `ScrollView`/`FlatList` carousels ([prop `useScrollView`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] [Callback methods](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#callbacks)
- [ ] [`ParallaxImage` component](https://github.com/archriss/react-native-snap-carousel#parallaximage-component)
- [ ] [`Pagination` component](https://github.com/archriss/react-native-snap-carousel#pagination-component)
- [ ] [Layouts and custom interpolations](https://github.com/archriss/react-native-snap-carousel#layouts-and-custom-interpolations)

### CODE REVIEW

**Comment by CarbonC** [comment]
Fix https://github.com/archriss/react-native-snap-carousel/issues/703

**Comment by MadeinFrance** [comment]
Tested it works.

**Comment by bfaulk96** [comment]
@bd-arc What are the ramifications of removing that z-index calculation for FlatLists?

**Comment by bd-arc** [comment]
@bfaulk96 Well, this might prove critical with advanced layouts.

Could you please let me know what happens if you set prop `layout` to `stack` or `tinder`?

In my opinion, the root issue has more to do with `this._getCustomDataLength()` that might not be updated when you add items dynamically than with the `zIndex` itself...

**Comment by CarbonC** [comment]
I think zindex problem can be fixed in another way, probably with native code. The fact is that this zindex code was a dirty workaround on a react native issue, so I think we should remove it and find another workaround for that. I dont understand the carousel's code in depth but i would say that this._getCustomDataLength() is probably ok since everything seems to work on this PR...

**Comment by bfaulk96** [comment]
> @bfaulk96 Well, this might prove critical with advanced layouts.
> 
> Could you please let me know what happens if you set prop `layout` to `'stack'` or `'tinder'`?
> 
> In my opinion, the root issue has more to do with `this._getCustomDataLength()` that might not be updated when you add items dynamically than with the `zIndex` itself...

@bd-arc We don't use any advanced layouts in our project, so I'd need to make an example to test or fork yours. I can try and test this weekend!

**Comment by bd-arc** [comment]
@CarbonC I've been trying to cope with the Android zIndex issue as best I could for 3 years now... Let me assure you that this is not an easy task by any mean!

If you have any clue as to how we could solve it a different way, please put a most welcome end to this madness :-)

@bfaulk96 Thank you, I appreciate the effort!

However, you can probably save a lot of time by just adding `layout={'stack'}` to any of your existing carousels and testing it on both platforms afterwards ;-)

**Comment by bfaulk96** [comment]
@bd-arc It works for my use-case using the different layout styles. I'll post my configuration below
```jsx
            <Carousel
              ref={(c) => { this._carousel = c }}
              data={this.getStartedPages}
              bounces={!this.props.jumpToSignUp}
              useScrollView={false}
              loop={false}
              renderItem={this._renderCarouselItem}
              useExperimentalSnap
              firstItem={ this.props.jumpToSignUp ? this.getStartedPages.length - 1 : undefined }
              sliderWidth={Dimensions.get('window').width}
              disableIntervalMomentum={true}
              itemWidth={Dimensions.get('window').width}
              onScrollIndexChanged={async (newIndex) => { await this.pageChanged(newIndex) }}
            />
```

**Comment by CarbonC** [comment]
@bd-arc I sadly got no clue either :-( The fact that there is an open issue on main react native github open for 2 years is kinda depressing. I thought there was another way because i read too fast the comments on the RN issue, sorry :/ 
I don't know how important for your layouts is zindex, but i feel like the issue fixed by this PR is a big one and i really haven't found any other solutions :-(

**Comment by bd-arc** [comment]
Should work properly in `4.0.0-beta.5`.

See [this comment](https://github.com/archriss/react-native-snap-carousel/issues/703#issuecomment-663021150) for more info.

**Pull request closed without merging**
